"""Resolve ``auto`` values of a Robot Definition into concrete numbers.

``Form → Robot Definition → resolve → validate → generate``

The resolver never guesses hardware: every id must exist in the registry.
The result (:class:`ResolvedRobot`) is what generators and rules consume, and
it is serialised to ``robot.lock.yaml`` together with the registry/template
versions so a workspace can be regenerated byte-for-byte later.
"""
from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from . import __version__
from .calc import geometry as g
from .registry.loader import DriverManifest, HardwareRecord, Registry
from .schema.definition import Costmap, RobotDefinition


class ResolveError(Exception):
    pass


class ResolvedWheel(BaseModel):
    name: str
    joint: str
    x: float
    y: float
    side: int
    radius: float
    width: float
    mass: float
    inertia: dict[str, float]


class ResolvedCaster(BaseModel):
    name: str
    x: float
    y: float
    z: float
    radius: float


class ResolvedHardware(BaseModel):
    """A hardware instance joined with its registry record (and driver, if any)."""

    model_config = ConfigDict(arbitrary_types_allowed=True)
    id: str
    hw: str
    category: str
    name: str
    frame: str | None
    parent: str
    xyz: list[float]
    rpy: list[float]
    mass: float
    dims: list[float]
    inertia: dict[str, float]
    is_camera: bool
    optical_frame: str | None
    driver_package: str | None
    driver_apt: list[str]
    topic: str | None
    sensor: dict[str, Any] | None


class ResolvedChassis(BaseModel):
    length: float
    width: float
    height: float
    ground_clearance: float
    base_link_z: float  # base_footprint → base_link (axle height)
    box_center_z: float  # chassis box centre relative to base_link
    mass: float
    inertia: dict[str, float]


class ResolvedRobot(BaseModel):
    definition: RobotDefinition
    package_prefix: str
    robot_mass: float
    total_mass: float
    chassis: ResolvedChassis
    wheel_radius: float
    wheels: list[ResolvedWheel]
    casters: list[ResolvedCaster]
    hardware: list[ResolvedHardware]
    controller: str
    controller_joints: dict[str, str]
    holonomic: bool
    ekf: bool
    planner: str
    nav_controller: str
    costmap: Costmap
    footprint: list[list[float]]
    lidar_range: float | None
    capabilities: dict[str, Any]
    versions: dict[str, str]

    # generator convenience -------------------------------------------------
    @property
    def d(self) -> RobotDefinition:
        return self.definition

    def package(self, suffix: str) -> str:
        return f"{self.package_prefix}_{suffix}"


def _require_hw(reg: Registry, hw_id: str, what: str) -> HardwareRecord:
    rec = reg.hw(hw_id)
    if rec is None:
        raise ResolveError(f"{what}: hardware id '{hw_id}' is not in the registry")
    return rec


def resolve(defn: RobotDefinition, reg: Registry) -> ResolvedRobot:
    d = defn
    dims = d.mechanical.dims_m
    wheel_r = d.drive.wheels.diameter_m / 2.0
    distro = d.target.ros_distro

    # ---------------------------------------------------------------- hardware
    hardware: list[ResolvedHardware] = []
    hw_mass = 0.0
    lidar_range: float | None = None
    for inst in d.hardware:
        rec = _require_hw(reg, inst.hw, f"hardware[{inst.id}]")
        drv: DriverManifest | None = reg.driver(inst.hw, distro)
        hw_mass += rec.mass_kg
        is_cam = rec.category in {"depth_camera", "rgb_camera"}
        sensor = rec.sensor.model_dump() if rec.sensor else None
        if rec.category == "lidar" and rec.sensor and rec.sensor.range_m:
            lidar_range = max(lidar_range or 0.0, rec.sensor.range_m)
        inertia = g.box_inertia(max(rec.mass_kg, 0.001), *rec.dims_m).as_dict()
        hardware.append(
            ResolvedHardware(
                id=inst.id, hw=inst.hw, category=rec.category, name=rec.name,
                frame=inst.frame, parent=inst.parent, xyz=inst.xyz, rpy=inst.rpy,
                mass=rec.mass_kg, dims=rec.dims_m, inertia=inertia, is_camera=is_cam,
                optical_frame=(f"{inst.frame}_optical" if (is_cam and inst.frame) else None),
                driver_package=(drv.package if drv else None),
                driver_apt=(drv.apt if drv else []),
                topic=(drv.topics.get("main") if drv and drv.topics else (rec.ros.topic if rec.ros else None)),
                sensor=sensor,
            )
        )

    motor = _require_hw(reg, d.drive.motor.hw, "drive.motor.hw")
    _require_hw(reg, d.drive.motor.driver, "drive.motor.driver")
    battery = _require_hw(reg, d.power.battery.hw, "power.battery.hw")
    _require_hw(reg, d.target.compute, "target.compute")
    hw_mass += motor.mass_kg * d.drive.motor.count + battery.mass_kg

    # -------------------------------------------------------------------- mass
    robot_mass = (
        g.estimate_robot_mass(hw_mass, dims.length, dims.width, dims.height)
        if d.mechanical.mass_kg.robot == "auto" else float(d.mechanical.mass_kg.robot)
    )
    total_mass = (
        g.r4(robot_mass + d.requirements.payload.max_kg)
        if d.mechanical.mass_kg.total == "auto" else float(d.mechanical.mass_kg.total)
    )

    # ----------------------------------------------------------------- chassis
    wheel_mass = g.r4(max(0.2, 0.02 * robot_mass / d.drive.motor.count))
    chassis_mass = g.r4(max(0.5, robot_mass - wheel_mass * d.drive.motor.count - hw_mass))
    chassis = ResolvedChassis(
        length=dims.length, width=dims.width, height=dims.height,
        ground_clearance=dims.ground_clearance,
        base_link_z=g.r4(wheel_r),
        box_center_z=g.r4(dims.ground_clearance + dims.height / 2.0 - wheel_r),
        mass=chassis_mass,
        inertia=g.box_inertia(chassis_mass, dims.length, dims.width, dims.height).as_dict(),
    )

    # ------------------------------------------------------------------ wheels
    wheels = [
        ResolvedWheel(
            name=w.name, joint=f"{w.name}_joint", x=w.x, y=w.y, side=w.side,
            radius=g.r4(wheel_r), width=d.drive.wheels.width_m, mass=wheel_mass,
            inertia=g.cylinder_inertia(wheel_mass, wheel_r, d.drive.wheels.width_m).as_dict(),
        )
        for w in g.wheel_poses(d.drive.type, d.drive.wheels.separation_m, d.drive.wheels.wheelbase_m)
    ]
    casters = []
    for i, c in enumerate(d.drive.casters):
        radius = g.caster_radius(wheel_r, dims.ground_clearance) if c.radius_m == "auto" else float(c.radius_m)
        casters.append(ResolvedCaster(name=f"caster_{i}", x=c.xyz[0], y=c.xyz[1], z=g.r4(radius - wheel_r), radius=radius))

    # ------------------------------------------------------------ ros profiles
    drive_prof = reg.drive_profiles.get(d.drive.type)
    if drive_prof is None:
        raise ResolveError(f"no drive profile '{d.drive.type}' in registry")
    nav_prof = reg.nav_profiles.get(d.ros.navigation.profile)
    if nav_prof is None:
        raise ResolveError(f"no nav profile '{d.ros.navigation.profile}' in registry")

    controller = drive_prof.controller if d.ros.control.controller == "auto" else d.ros.control.controller
    planner = drive_prof.nav_planner if d.ros.navigation.planner == "auto" else d.ros.navigation.planner
    nav_controller = drive_prof.nav_controller if d.ros.navigation.controller == "auto" else d.ros.navigation.controller

    cats = {h.category for h in hardware}
    has_encoder = "encoder" in cats or any(h.category == "motor_driver" for h in hardware)
    ekf = (("imu" in cats) and has_encoder) if d.ros.localization.ekf == "auto" else bool(d.ros.localization.ekf)

    # ----------------------------------------------------------------- costmap
    margin = d.ros.navigation.safety_margin_m
    if d.ros.navigation.costmap == "auto":
        local = g.local_costmap_size(
            d.requirements.motion.v_max, d.requirements.motion.a_max, dims.length,
            nav_prof.local_costmap_min_m, nav_prof.local_costmap_max_m,
        )
        obst = g.obstacle_range(lidar_range or 8.0, local, nav_prof.obstacle_range_factor)
        costmap = Costmap(
            resolution_m=nav_prof.resolution_m,
            local_size_m=local,
            inflation_radius_m=g.inflation_radius(dims.length, dims.width, margin, nav_prof.inflation_extra_m),
            obstacle_range_m=obst,
            raytrace_range_m=g.raytrace_range(obst, nav_prof.raytrace_extra_m),
        )
    else:
        costmap = d.ros.navigation.costmap

    capabilities = {
        "robot": d.meta.name,
        "drive": d.drive.type,
        "holonomic": drive_prof.holonomic,
        "features": list(d.ros.navigation.features),
        "sensors": sorted(cats & {"lidar", "depth_camera", "rgb_camera", "imu", "gnss", "ultrasonic"}),
        "digital_inputs": {str(k): v for k, v in d.io.DI.items()},
        "digital_outputs": {str(k): v for k, v in d.io.DO.items()},
        "comms": list(d.comms),
        "max_speed": d.requirements.motion.v_max,
    }

    return ResolvedRobot(
        definition=d,
        package_prefix=d.meta.package_prefix,
        robot_mass=robot_mass,
        total_mass=total_mass,
        chassis=chassis,
        wheel_radius=g.r4(wheel_r),
        wheels=wheels,
        casters=casters,
        hardware=hardware,
        controller=controller,
        controller_joints=drive_prof.joints,
        holonomic=drive_prof.holonomic,
        ekf=ekf,
        planner=planner,
        nav_controller=nav_controller,
        costmap=costmap,
        footprint=g.footprint_polygon(dims.length, dims.width, margin),
        lidar_range=lidar_range,
        capabilities=capabilities,
        versions={
            "generator": __version__,
            "schema": "1",
            "registry": reg.content_hash(),
            "ros_distro": distro,
        },
    )
