"""Generator plugin base.

A generator is a small class with an ``id`` and ``render(ctx) -> list[GeneratedFile]``.
Templates are Jinja2 files under ``generators/templates/<generator id>/``.
Generators never read the definition file directly — they only see the
:class:`ResolvedRobot` (so every ``auto`` is already a number).
"""
from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Protocol

from jinja2 import Environment, FileSystemLoader, StrictUndefined

from ..resolve import ResolvedRobot

TEMPLATES_DIR = Path(__file__).parent / "templates"


@dataclass(frozen=True)
class GeneratedFile:
    path: str  # relative to the workspace root, POSIX separators
    content: str
    executable: bool = False


@dataclass
class GenContext:
    resolved: ResolvedRobot
    definition_name: str
    definition_digest: str
    env: Environment = field(init=False)

    def __post_init__(self) -> None:
        self.env = Environment(
            loader=FileSystemLoader(str(TEMPLATES_DIR)),
            undefined=StrictUndefined,
            trim_blocks=True,
            lstrip_blocks=True,
            keep_trailing_newline=True,
            autoescape=False,
        )
        self.env.filters["f4"] = lambda x: f"{float(x):.4f}"
        self.env.filters["sci"] = lambda x: f"{float(x):.6g}"
        self.env.filters["vec"] = lambda v: " ".join(f"{float(x):.4f}" for x in v)

    @property
    def header(self) -> str:
        r = self.resolved
        return (
            f"GENERATED by TESR Robot Builder {r.versions['generator']} from {self.definition_name}@{self.definition_digest} "
            f"(registry {r.versions['registry']}) — do not edit; put changes in overrides/ and regenerate"
        )

    def render(self, template: str, path: str, executable: bool = False, **extra) -> GeneratedFile:
        tpl = self.env.get_template(template)
        content = tpl.render(r=self.resolved, d=self.resolved.definition, header=self.header, **extra)
        return GeneratedFile(path=path, content=content, executable=executable)


class Generator(Protocol):
    id: str
    description: str

    def render(self, ctx: GenContext) -> list[GeneratedFile]: ...


_GENERATORS: dict[str, Generator] = {}


def register(gen: Generator) -> Generator:
    if gen.id in _GENERATORS:
        raise ValueError(f"duplicate generator id {gen.id}")
    _GENERATORS[gen.id] = gen
    return gen


def all_generators() -> list[Generator]:
    """Pipeline order is the registration order (description → bringup → …)."""
    return list(_GENERATORS.values())
